FROM alpine:3.15

RUN apk update

RUN apk add pcre-dev pcre-tools python2 python2-dev gcc g++ zlib-dev jpeg-dev linux-headers openssl-dev dwarf-tools

RUN python2 -m ensurepip

RUN pip2 install --upgrade pip setuptools

RUN pip2 install distorm3 yara-python pycryptodome pillow openpyxl ujson