FROM alpine:3.17

RUN apk update

RUN apk add git python3 python3-dev py-pip snappy-dev make gcc capstone musl-dev linux-headers openssl-dev libusb-dev

RUN pip3 install wheel

WORKDIR /tmp
# https://stackoverflow.com/a/58801213
ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache
RUN git clone https://github.com/volatilityfoundation/volatility3.git && cd volatility3/ && pip3 install .[full]
RUN rm -rf volatility3